### ISSUE TITLE
云闪付扫码支付成功后异常退出

### ISSUE THREAD

**Issue by dreamy06** [eritpchy/WechatFp#199]
模块版本：zygisk 5.2.0
云闪付版本：10.0.8(3341)
遇到问题：通过扫码支付成功后，云闪付会异常退出；另外此场景切换付款方式后未能触发指纹验证

**Comment by eritpchy** [comment]
5.0.2? 请更新到5.2.0

**Comment by eritpchy** [comment]
5.2.0目前实测是可以切换付款方式的, 你不可以的话麻烦录个小视频

**Comment by eritpchy** [comment]
需要你扫的那个二维码图片

**Comment by eritpchy** [comment]
[zygisk-module-xfingerprint-pay-unionpay-v5.2.1-release.zip](https://github.com/eritpchy/FingerprintPay/files/15478812/zygisk-module-xfingerprint-pay-unionpay-v5.2.1-release.zip)
试试

**Comment by eritpchy** [comment]
这个需要你抓日志了

**Comment by eritpchy** [comment]
[zygisk-module-xfingerprint-pay-unionpay-v5.2.2-release.zip](https://github.com/eritpchy/FingerprintPay/files/15479434/zygisk-module-xfingerprint-pay-unionpay-v5.2.2-release.zip)
试试

**Comment by eritpchy** [comment]
[zygisk-module-xfingerprint-pay-unionpay-v5.2.3-release.zip](https://github.com/eritpchy/FingerprintPay/files/15480495/zygisk-module-xfingerprint-pay-unionpay-v5.2.3-release.zip)
试试

**Comment by eritpchy** [comment]
好的
