### ISSUE TITLE
增加深色模式并减少卡顿

### ISSUE THREAD

**Issue by Keeperorowner** [eritpchy/WechatFp#208]
允许各个应用的设置ui，跟随应用设置，自动切换进入深色模式

**Comment by eritpchy** [comment]
目前设置界面均采用免维护以及较为通用的方式实现, 载入慢属于合理现象. 你有想法可以自行提pr合并
支付ui目前是做了夜间模式跟随的, 而设置ui不属于重点维护对象, 默认都是跟随应用当前context, 有部分应用显示为白色, 个人可以接受. 你有想法可以自行提pr合并

**Comment by Nimpip** [comment]
但是我感觉是一个bug吧，第1次打开设置的时候是指纹支付选项没有延迟的，第2次打开才会有明显的卡顿

**Comment by eritpchy** [comment]
每台机表现不一样, 录屏看看

**Comment by Nimpip** [comment]
https://github.com/user-attachments/assets/0ac64863-9a30-4ee3-8618-b264fadec810

第1次打开设置选项的显示是没有延迟的，第2次以及之后的打开，有一个很明显的卡顿的过程
